name: Build All Chips

on:
  push:
    paths:
      - 'wokwi/chips/**'
      - '.github/workflows/**'

jobs:
  build-chips:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug: Lista de arquivos
        run: find .

      - name: Compilar chips com Wokwi Clang
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: |
            wokwi/chips/bh1750/bh1750.chip.c
            wokwi/chips/ads1115/ads1115.chip.c
            # Adicione outros chips conforme a pasta

      - name: Ajustar permissões
        run: sudo chown -R runner:runner wokwi/chips

      - name: Upload artefatos compilados
        uses: actions/upload-artifact@v4
        with:
          name: compiled-chips
          path: wokwi/chips/**/*.chip.wasm