name: Build All Chips

on:
  push:
  workflow_dispatch:

jobs:
  build-chips:
    name: Build ${{ matrix.chip }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        chip: [ads1115, bh1750, opamp]  # Adicione os chips que tiver na pasta wokwi/chips

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build chip ${{ matrix.chip }}
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: wokwi/chips/${{ matrix.chip }}/src/main.c
          chip-json: wokwi/chips/${{ matrix.chip }}/chip.json

      - name: Organize output files
        run: |
          mkdir -p wokwi/chips/${{ matrix.chip }}/dist
          mv dist/chip.wasm wokwi/chips/${{ matrix.chip }}/dist/${{ matrix.chip }}.chip.wasm
          mv dist/chip.json wokwi/chips/${{ matrix.chip }}/dist/${{ matrix.chip }}.chip.json

      - name: Upload artifacts for ${{ matrix.chip }}
        uses: actions/upload-artifact@v4
        with:
          name: chip-${{ matrix.chip }}
          path: wokwi/chips/${{ matrix.chip }}/dist/