name: Build All Chips

on:
  push:
    paths:
      - 'wokwi/chips/**'
      - '.github/workflows/**'

jobs:
  build-chips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List .chip.c files
        run: |
          echo "Procurando arquivos .chip.c:"
          find wokwi/chips -name "*.chip.c"

      - name: Compile all .chip.c files
        run: |
          for file in $(find wokwi/chips -name "*.chip.c"); do
            base="${file%.chip.c}"
            echo "Compilando $file → ${base}.chip.wasm"
            clang --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export-all -I wokwi -o "${base}.chip.wasm" "$file" || echo "Erro ao compilar $file"
          done


      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-chips
          path: wokwi/chips/**/*.wasm
