name: Build All Custom Chips

on:
  push:
  workflow_dispatch:

jobs:
  build-all-chips:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile each chip in wokwi/chips/*
        shell: bash
        run: |
          for dir in wokwi/chips/*/; do
            chip_name=$(basename "$dir")
            echo "🔧 Compilando chip: $chip_name"
            
            # Define caminhos
            chip_c="$dir/${chip_name}.chip.c"
            chip_json="$dir/${chip_name}.chip.json"
            wasm_out="$dir/${chip_name}.chip.wasm"
            
            # Compilar
            if [ -f "$chip_c" ]; then
              echo "📦 Compilando $chip_c → $wasm_out"
              wokwi/wokwi-chip-clang-action@main \
                --sources "$chip_c" \
                --output "$wasm_out"
            else
              echo "⚠️ Arquivo $chip_c não encontrado. Pulando..."
              continue
            fi

            # Verifica se chip.json existe
            if [ -f "$chip_json" ]; then
              echo "✅ JSON encontrado: $chip_json"
            else
              echo "⚠️ JSON não encontrado: $chip_json"
            fi
          done

      - name: Upload todos os .wasm e .json como artefatos
        uses: actions/upload-artifact@v3
        with:
          name: all-chips
          path: wokwi/chips/**/**/*.chip.*