name: Build All Chips

on:
  push:
    paths:
      - 'wokwi/chips/**'
      - 'wokwi/wokwi-api.h'
      - '.github/workflows/**'

jobs:
  build-chips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Mostrar estrutura de diretórios (debug)
        run: |
          echo "Diretório atual:"
          pwd
          echo "Conteúdo completo do projeto:"
          find . -type f

      - name: Verificar se wokwi-api.h existe
        run: |
          if [ -f wokwi/wokwi-api.h ]; then
            echo "wokwi-api.h encontrado!"
          else
            echo "ERRO: wokwi-api.h não encontrado em wokwi/"
            exit 1
          fi

      - name: Compilar todos os .chip.c → .wasm
        run: |
          WOKWI_INCLUDE="$(pwd)/wokwi"
          for file in $(find wokwi/chips -name "*.chip.c"); do
            base="${file%.chip.c}"
            echo "Compilando $file → ${base}.chip.wasm"
            clang --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export-all -I "$WOKWI_INCLUDE" -o "${base}.chip.wasm" "$file" || echo "Erro ao compilar $file"
          done

      - name: Upload arquivos .wasm como artefato
        uses: actions/upload-artifact@v4
        with:
          name: compiled-chips
          path: wokwi/chips/**/*.wasm