name: Build All Chips

on:
  push:
    paths:
      - 'wokwi/chips/**'
      - '.github/workflows/**'

jobs:
  build-chips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Mostrar estrutura de diretórios (debug)
        run: |
          echo "Diretório atual: $(pwd)"
          echo "Conteúdo completo do projeto:"
          find . -type f

      - name: Verificar se wokwi-api.h existe
        run: |
          if [ -f wokwi/chips/wokwi-api.h ]; then
            echo "✅ wokwi-api.h encontrado"
          else
            echo "❌ ERRO: wokwi-api.h não encontrado em wokwi/chips/"
            exit 1
          fi

      - name: Compilar todos os .chip.c → .chip.wasm
        run: |
          INCLUDE_PATH="$(pwd)/wokwi/chips"
          for file in $(find wokwi/chips -name "*.chip.c"); do
            base="${file%.chip.c}"
            out="${base}.chip.wasm"
            echo "Compilando  $file → $out"
            clang \
              --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export-all \
              -I "$INCLUDE_PATH" \
              -o "$out" "$file" \
              || { echo "❌ Erro ao compilar $file"; exit 1; }
            sudo chown runner:runner "$out"
          done

      - name: Ajustar permissões de pasta chips
        run: |
          sudo chown -R runner:runner wokwi/chips

      - name: Upload dos arquivos compilados como artefato
        uses: actions/upload-artifact@v4
        with:
          name: compiled-chips
          path: |
            wokwi/chips/**/*.chip.wasm
