name: Build All Chips

on:
  push:
  workflow_dispatch:

jobs:
  build-all-chips:
    name: Build All Chips
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Find and build each chip
        run: |
          find wokwi/chips -maxdepth 1 -mindepth 1 -type d | while read chip_dir; do
            echo "\n🔧 Building chip in $chip_dir"
            chip_name=$(basename "$chip_dir")

            if [ -f "$chip_dir/src/main.c" ]; then
              echo "→ Compiling $chip_name..."
              wokwi/wokwi-chip-clang-action@main <<EOF > temp.yml
              name: Temp Build
              on: [push]
              jobs:
                build:
                  runs-on: ubuntu-22.04
                  steps:
                    - uses: actions/checkout@v3
                    - uses: wokwi/wokwi-chip-clang-action@main
                      with:
                        sources: "$chip_dir/src/main.c"
EOF
              echo "✅ Compiled $chip_name"

              mkdir -p "$chip_dir/dist"
              cp "$chip_dir/chip.json" "$chip_dir/dist/$chip_name.chip.json"
              cp dist/chip.wasm "$chip_dir/dist/$chip_name.chip.wasm"
            else
              echo "⚠️ No main.c found in $chip_dir/src"
            fi
          done

      - name: Upload all artifacts
        uses: actions/upload-artifact@v3
        with:
          name: all-chips
          path: wokwi/chips/**/dist/*.chip.*