name: Build All Chips

on:
  push:
    paths:
      - 'wokwi/chips/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-chips:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build all chips
        run: |
          ROOT_DIR="wokwi/chips"
          for chip_dir in "$ROOT_DIR"/*/; do
            CHIP_NAME=$(basename "$chip_dir")
            CHIP_C="$chip_dir/${CHIP_NAME}.chip.c"
            CHIP_JSON="$chip_dir/${CHIP_NAME}.chip.json"
            DIST_DIR="$chip_dir/dist"
            WASM_FILE="${DIST_DIR}/${CHIP_NAME}.chip.wasm"

            echo "→ Compilando $CHIP_NAME"
            mkdir -p "$DIST_DIR"

            if [ -f "$CHIP_C" ] && [ -f "$CHIP_JSON" ]; then
              clang --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export-all \
                -I "$ROOT_DIR" -o "$WASM_FILE" "$CHIP_C"
              cp "$CHIP_JSON" "$DIST_DIR/"
              echo "✔️  $CHIP_NAME compilado com sucesso!"
            else
              echo "⚠️  Pulando $CHIP_NAME: arquivos .chip.c ou .chip.json ausentes."
            fi
          done

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-chips
          path: |
            wokwi/chips/*/dist/*.chip.wasm
            wokwi/chips/*/dist/*.chip.json
