name: Build All Chips

on:
  push:
  workflow_dispatch:

jobs:
  build-all-chips:
    name: Build All Chips
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        chip: [ads1115, bh1750, opamp] # adicione mais chips aqui conforme necessário

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build chip - ${{ matrix.chip }}
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: wokwi/chips/${{ matrix.chip }}/src/main.c
          chip-json: wokwi/chips/${{ matrix.chip }}/chip.json

      - name: Fix permissions and move compiled files
        run: |
          CHIP_ID=${{ matrix.chip }}
          sudo chown -R runner:runner dist
          mkdir -p wokwi/chips/$CHIP_ID/dist
          mv dist/chip.wasm "wokwi/chips/$CHIP_ID/dist/${CHIP_ID}.chip.wasm"
          mv chip.json "wokwi/chips/$CHIP_ID/dist/${CHIP_ID}.chip.json"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.chip }}
          path: |
            wokwi/chips/${{ matrix.chip }}/dist/${{ matrix.chip }}.chip.wasm
            wokwi/chips/${{ matrix.chip }}/dist/${{ matrix.chip }}.chip.json
