name: Build All Chips

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Compile all chips inside wokwi/chips/*
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: |
            wokwi/chips/*/*.chip.c

      - name: Rename and move outputs to proper dist folders
        run: |
          for dir in wokwi/chips/*/; do
            name=$(basename "$dir")
            wasm_file="dist/chip.wasm"
            json_file="chip.json"

            if [[ -f "$wasm_file" ]]; then
              mkdir -p "$dir/dist"
              cp "$wasm_file" "$dir/dist/${name}.chip.wasm"
              echo "✅ $wasm_file copiado para $dir/dist/${name}.chip.wasm"
            else
              echo "⚠️ $wasm_file não encontrado para $name"
            fi

            if [[ -f "$json_file" ]]; then
              cp "$json_file" "$dir/dist/${name}.chip.json"
              echo "✅ $json_file copiado para $dir/dist/${name}.chip.json"
            else
              echo "⚠️ $json_file não encontrado para $name"
            fi
          done

      - name: Upload All Chips
        uses: actions/upload-artifact@v4
        with:
          name: all-chips
          path: wokwi/chips/*/dist/

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all chips
        uses: actions/download-artifact@v4
        with:
          name: all-chips
          path: chips-release

      - name: Create a zip archive
        run: cd chips-release && zip -9 -r ../chips.zip .

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: chips.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true