name: Build All Chips

on:
  push:
    paths:
      - 'wokwi/chips/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-chips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang

      - name: Build all chips in wokwi/chips
        run: |
          ROOT_DIR="$(pwd)/wokwi/chips"
          for chip_dir in "$ROOT_DIR"/*/; do
            CHIP_NAME=$(basename "$chip_dir")
            SRC_FILE="$chip_dir/${CHIP_NAME}.chip.c"
            JSON_FILE="$chip_dir/${CHIP_NAME}.chip.json"
            OUT_FILE="$chip_dir/${CHIP_NAME}.chip.wasm"

            if [[ -f "$SRC_FILE" ]]; then
              echo "Compilando $SRC_FILE → $OUT_FILE"
              clang --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export-all -I "$ROOT_DIR" -o "$OUT_FILE" "$SRC_FILE" || echo "Erro ao compilar $SRC_FILE"
            else
              echo "Arquivo fonte $SRC_FILE não encontrado. Pulando."
            fi

            if [[ ! -f "$JSON_FILE" ]]; then
              echo "AVISO: $JSON_FILE não encontrado"
            fi
          done

      - name: List all .wasm outputs (debug)
        run: find wokwi/chips -name "*.wasm"

      - name: Upload all .wasm files
        uses: actions/upload-artifact@v4
        with:
          name: compiled-chips
          path: wokwi/chips/**/*.wasm